Improve typing of RunResult
yeoman/yeoman-test pull request #165
Opened 2023-01-19 16:08 UTC by jvasseur

This PR adds 2 changes:
 - Add default for generator type in RunResult: this allows typing the result as juste `RunResult` in places where we don't care of the type of the generator.
- Improve typing in helpers to make typescript better at infering the generator type: when doing `hepers.create(MyGenerator)`, typescript will now correctly infer the result as `RunResult<MyGenerator>`

2023-01-19 19:24 UTC, mischah requested changes
Hej, thanks for the PR. Please have a look at the output of the failing builds. There are some type errors 😬

2023-01-20 11:10 UTC, mischah approved these changes
Jop 👍🏻 
The Integration Build failed before.

Still needs a review of [mshima](https://github.com/mshima) 😗

2023-01-20 11:11 UTC, mischah approved these changes

2023-01-24 17:34 UTC, merged

2023-01-24 17:35 UTC, mshima commented
Trusting @mischah review.